"""
Province terrain type generator for World Ablaze AI.

Reads HOI4's map/definition.csv to extract terrain types for each province
and generates a precomputed terrain mapping file.
"""

from pathlib import Path
from typing import Any, Dict, List
import sys

sys.path.insert(0, str(Path(__file__).parent.parent))

from core import parse_definition_for_terrain
from map_generators.base import BaseMapGenerator, GeneratorConfig

# World Ablaze terrain type mapping (from WA_AI_MAP_effects.txt)
# These must match the constants defined in WA_AI_MAP_startup
WA_TERRAIN_TYPES = {
    "unknown": 0,
    "plains": 1,
    "desert": 2,
    "marsh": 3,
    "jungle": 4,
    "forest": 5,
    "urban": 6,
    "hills": 7,
    "mountain": 8,
    "ocean": 9,
    "lakes": 9,
    "lake": 9,
    "sea": 9,
    # Additional terrain types found in World Ablaze definition.csv
    "marsh_forest": 3,
    "arid": 2,
    "island": 1,
    "atoll": 1,
    "savanna": 1,
    "steppe": 1,
    "tundra": 1,
    # Impassable terrain types
    "desert_impassable": 8,
    "jungle_impassable": 8,
    "mountain_impassable": 8,
    "plains_impassable": 8,
    "forest_impassable": 8,
}


def terrain_to_wa_type(terrain: str) -> int:
    """
    Convert terrain name to World Ablaze terrain type number.

    Args:
        terrain: Terrain name from definition.csv.

    Returns:
        World Ablaze terrain type constant (0-9).
    """
    terrain_lower = terrain.lower().strip()

    if terrain_lower in WA_TERRAIN_TYPES:
        return WA_TERRAIN_TYPES[terrain_lower]

    # Default to plains for unknown types
    return WA_TERRAIN_TYPES["plains"]


class ProvinceTerrainGenerator(BaseMapGenerator):
    """Generator for province terrain type mappings."""

    @property
    def name(self) -> str:
        return "province_terrain"

    @property
    def description(self) -> str:
        return "Generate province terrain mappings for World Ablaze AI"

    def get_output_filename(self) -> str:
        return "WA_AI_MAP_province_terrain.txt"

    def get_required_inputs(self) -> List[Path]:
        return [self.config.map_dir / "definition.csv"]

    def process(self) -> Dict[str, Any]:
        """Parse definition.csv and map terrain types."""
        self.log_step("Parsing terrain data from definition.csv...")
        province_terrain = parse_definition_for_terrain(
            self.config.map_dir / "definition.csv"
        )

        # Count terrain distribution for logging
        terrain_counts: Dict[str, int] = {}
        for terrain in province_terrain.values():
            terrain_counts[terrain] = terrain_counts.get(terrain, 0) + 1

        self.logger.info("Terrain distribution:")
        for terrain, count in sorted(terrain_counts.items(), key=lambda x: -x[1]):
            wa_type = terrain_to_wa_type(terrain)
            self.logger.info(f"  {terrain}: {count} provinces (WA type {wa_type})")

        return {"province_terrain": province_terrain}

    def format_output(self, data: Dict[str, Any]) -> str:
        """Format terrain data for output file."""
        province_terrain = data["province_terrain"]

        lines: List[str] = []
        lines.append(
            "############################################################################################################"
        )
        lines.append("#    World Ablaze AI - Province Terrain Types")
        lines.append("#    Auto-generated by map_generators")
        lines.append(
            "#    DO NOT EDIT MANUALLY - Regenerate using: python run_generators.py province_terrain"
        )
        lines.append(
            "############################################################################################################"
        )
        lines.append("")
        lines.append("WA_AI_MAP_set_province_terrain_type = {")

        for province_id in sorted(province_terrain.keys()):
            terrain_name = province_terrain[province_id]
            terrain_type = terrain_to_wa_type(terrain_name)
            lines.append(
                f"    set_variable = {{ global.WA_AI_MAP_province_terrain_type^{province_id} = {terrain_type} }}"
            )

        lines.append("}")

        return "\n".join(lines)


def main() -> int:
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate province terrain mappings for World Ablaze AI."
    )
    parser.add_argument(
        "--map-dir",
        type=Path,
        default=Path("../map"),
        help="Path to the map folder",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("../common/scripted_effects"),
        help="Output directory",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    parser.add_argument("--dry-run", action="store_true")

    args = parser.parse_args()

    config = GeneratorConfig(
        map_dir=args.map_dir,
        output_dir=args.output_dir,
        verbose=args.verbose,
        dry_run=args.dry_run,
    )

    generator = ProvinceTerrainGenerator(config)
    result = generator.run()

    return 0 if result.success else 1


if __name__ == "__main__":
    sys.exit(main())
